from __future__ import annotations

from enum import StrEnum


class IngestStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    WARNING = "WARNING"


class MatchMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    PROBABILISTIC = "PROBABILISTIC"
    HYBRID = "HYBRID"


class MatchTier(StrEnum):
    EXACT = "EXACT"
    STRONG = "STRONG"
    WEAK = "WEAK"


class MatchDecisionType(StrEnum):
    AUTO_MERGE = "AUTO_MERGE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    NON_MATCH = "NON_MATCH"
    CREATE_NEW_GOLDEN = "CREATE_NEW_GOLDEN"
    VALIDATION_FAILED = "VALIDATION_FAILED"


class ReviewStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    CLOSED = "CLOSED"


class ReviewDecisionType(StrEnum):
    APPROVE_MERGE = "APPROVE_MERGE"
    REJECT_MERGE = "REJECT_MERGE"
    REQUEST_MORE_INFO = "REQUEST_MORE_INFO"


class GoldenRecordStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUPERSEDED = "SUPERSEDED"
    MERGED = "MERGED"


class LinkStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    REVOKED = "REVOKED"


class MergeEventType(StrEnum):
    AUTO = "AUTO"
    MANUAL = "MANUAL"
    UNMERGE = "UNMERGE"
    CREATE_GOLDEN = "CREATE_GOLDEN"


class HistoryEventType(StrEnum):
    PRIMARY_OVERRIDE = "PRIMARY_OVERRIDE"
    GOLDEN_MERGE = "GOLDEN_MERGE"
    MERGE_ROLLBACK = "MERGE_ROLLBACK"
    TIMELINE_QUERY = "TIMELINE_QUERY"


class SafetyFlag(StrEnum):
    VERIFIED_FIELD_CONFLICT = "VERIFIED_FIELD_CONFLICT"
    LOW_EVIDENCE = "LOW_EVIDENCE"
    HIGH_RISK_ATTRIBUTE = "HIGH_RISK_ATTRIBUTE"
    TIER1_IDENTIFIER_CONFLICT = "TIER1_IDENTIFIER_CONFLICT"
    DATE_OF_BIRTH_CONFLICT = "DATE_OF_BIRTH_CONFLICT"
    MULTIPLE_HIGH_CONFIDENCE_CANDIDATES = "MULTIPLE_HIGH_CONFIDENCE_CANDIDATES"
    LOW_TOP_CANDIDATE_GAP = "LOW_TOP_CANDIDATE_GAP"
    SOURCE_ALREADY_LINKED_ELSEWHERE = "SOURCE_ALREADY_LINKED_ELSEWHERE"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNTRUSTED_SOURCE_FOR_AUTO_MERGE = "UNTRUSTED_SOURCE_FOR_AUTO_MERGE"


class SourceTrustLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class DuplicateSeverity(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    BLOCKED = "BLOCKED"


class DuplicateCandidateStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    CONFIRMED_DUPLICATE = "CONFIRMED_DUPLICATE"
    NOT_DUPLICATE = "NOT_DUPLICATE"
    DISMISSED = "DISMISSED"
    STALE = "STALE"
    MERGED = "MERGED"
