from __future__ import annotations

from typing import Protocol

from .models import AuditEvent, GoldenRecord, ManualReviewTask, MatchRun, MergeHistoryEvent, RecordLink, SourceRecord


class IRERepository(Protocol):
    def initialize_storage(self) -> None: ...

    def validate_storage(self) -> None: ...

    def append_source_record(self, record: SourceRecord) -> None: ...

    def find_source_records_by_external_key(self, source_system: str, source_pk: str) -> list[SourceRecord]: ...

    def find_source_record_by_payload_hash(
        self, source_system: str, source_pk: str, payload_hash: str
    ) -> SourceRecord | None: ...

    def load_golden_records(self) -> list[GoldenRecord]: ...

    def find_golden_record(self, golden_record_id: str) -> GoldenRecord | None: ...

    def save_golden_records(self, records: list[GoldenRecord]) -> None: ...

    def load_record_links(self) -> list[RecordLink]: ...

    def save_record_links(self, links: list[RecordLink]) -> None: ...

    def append_match_run(self, run: MatchRun) -> None: ...

    def load_manual_review_tasks(self) -> list[ManualReviewTask]: ...

    def save_manual_review_tasks(self, tasks: list[ManualReviewTask]) -> None: ...

    def append_merge_history_event(self, event: MergeHistoryEvent) -> None: ...

    def append_audit_event(self, event: AuditEvent) -> None: ...
