from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

from .models import (
    AuditEvent,
    GoldenRecord,
    ManualReviewTask,
    MatchRun,
    MergeEvent,
    MergeHistoryEvent,
    PrimaryOverrideEvent,
    RecordLink,
    RollbackEvent,
    SourceRecord,
)


class IRERepository(Protocol):
    def initialize_storage(self) -> None: ...

    def validate_storage(self) -> None: ...

    def append_source_record(self, record: SourceRecord) -> None: ...

    def find_source_records_by_external_key(self, source_system: str, source_pk: str) -> list[SourceRecord]: ...

    def find_source_record_by_payload_hash(
        self, source_system: str, source_pk: str, payload_hash: str
    ) -> SourceRecord | None: ...

    def load_source_records(self) -> list[SourceRecord]: ...

    def find_source_record(self, source_record_id: str) -> SourceRecord | None: ...

    def load_golden_records(self) -> list[GoldenRecord]: ...

    def find_golden_record(self, golden_record_id: str) -> GoldenRecord | None: ...

    def save_golden_records(self, records: list[GoldenRecord]) -> None: ...

    def load_record_links(self) -> list[RecordLink]: ...

    def save_record_links(self, links: list[RecordLink]) -> None: ...

    def append_match_run(self, run: MatchRun) -> None: ...

    def load_match_runs(self) -> list[MatchRun]: ...

    def find_match_run(self, run_id: str) -> MatchRun | None: ...

    def load_merge_history_events(self) -> list[MergeHistoryEvent]: ...

    def load_audit_events(self) -> list[AuditEvent]: ...

    def load_manual_review_tasks(self) -> list[ManualReviewTask]: ...

    def save_manual_review_tasks(self, tasks: list[ManualReviewTask]) -> None: ...

    def append_merge_history_event(self, event: MergeHistoryEvent) -> None: ...

    def append_audit_event(self, event: AuditEvent) -> None: ...

    def save_golden_record(self, record: GoldenRecord) -> None: ...

    def save_record_link(self, link: RecordLink) -> None: ...

    def save_merge_event(self, event: MergeEvent) -> None: ...

    def load_merge_events(self) -> list[MergeEvent]: ...

    def load_merge_event(self, merge_id: str) -> MergeEvent | None: ...

    def save_primary_override_event(self, event: PrimaryOverrideEvent) -> None: ...

    def load_primary_override_events(self) -> list[PrimaryOverrideEvent]: ...

    def save_rollback_event(self, event: RollbackEvent) -> None: ...

    def load_rollback_events(self) -> list[RollbackEvent]: ...

    def find_rollback_for_merge(self, merge_id: str) -> RollbackEvent | None: ...

    def atomic_update(self) -> AbstractContextManager["IRERepository"]: ...
