CREATE TABLE identities (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_key VARCHAR2(64) NOT NULL UNIQUE,
  hkid VARCHAR2(50),
  staff_id VARCHAR2(50),
  student_id VARCHAR2(50),
  badge_id VARCHAR2(50),
  email VARCHAR2(255),
  phone VARCHAR2(100),
  first_name VARCHAR2(255),
  last_name VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_identities_hkid ON identities(hkid);
CREATE INDEX idx_identities_student_id ON identities(student_id);
CREATE INDEX idx_identities_staff_id ON identities(staff_id);
CREATE INDEX idx_identities_email ON identities(email);
