-- V1: Create all IRE tables (H2-compatible for dev/test, Oracle-compatible for prod)
-- For Oracle production, replace AUTO_INCREMENT with SEQUENCE + TRIGGER

-- Golden identity records
CREATE TABLE IF NOT EXISTS IDENTITIES (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    GOLDEN_ID      VARCHAR(64)  NOT NULL UNIQUE,
    HKID           VARCHAR(20),
    STAFF_ID       VARCHAR(32),
    STUDENT_ID     VARCHAR(32),
    EMAIL          VARCHAR(255) NOT NULL,
    FIRST_NAME     VARCHAR(100),
    LAST_NAME      VARCHAR(100),
    PHONE          VARCHAR(30),
    STATUS         VARCHAR(20)  DEFAULT 'ACTIVE',
    CONFIDENCE_SCORE DOUBLE,
    PRIMARY_SOURCE VARCHAR(50),
    CREATED_BY     VARCHAR(100),
    CREATED_DATE   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY     VARCHAR(100),
    UPDATED_DATE   TIMESTAMP
);

-- Source system links
CREATE TABLE IF NOT EXISTS IDENTITY_LINKS (
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    GOLDEN_ID        VARCHAR(64)  NOT NULL,
    SOURCE_SYSTEM    VARCHAR(50)  NOT NULL,
    SOURCE_ID        VARCHAR(100) NOT NULL,
    CREDIBILITY_SCORE DOUBLE,
    MATCH_TIER       VARCHAR(20),
    STATUS           VARCHAR(20)  DEFAULT 'ACTIVE',
    CREATED_DATE     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE     TIMESTAMP
);

-- Identity graph relationships
CREATE TABLE IF NOT EXISTS IDENTITY_GRAPH (
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE_GOLDEN_ID     VARCHAR(64) NOT NULL,
    TARGET_GOLDEN_ID     VARCHAR(64) NOT NULL,
    RELATIONSHIP_TYPE    VARCHAR(50),
    RELATIONSHIP_STRENGTH DOUBLE,
    STATUS               VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- Manual review queue
CREATE TABLE IF NOT EXISTS MANUAL_REVIEWS (
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    REVIEW_ID           VARCHAR(64)  NOT NULL UNIQUE,
    INCOMING_PAYLOAD    CLOB,
    CANDIDATE_GOLDEN_ID VARCHAR(64),
    CONFIDENCE_SCORE    DOUBLE,
    SOURCE_SYSTEM       VARCHAR(50),
    STATUS              VARCHAR(30)  DEFAULT 'PENDING',
    REVIEWER            VARCHAR(100),
    REVIEW_NOTES        CLOB,
    CREATED_DATE        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_DATE       TIMESTAMP
);

-- Audit logs
CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTION       VARCHAR(100) NOT NULL,
    ENTITY_TYPE  VARCHAR(50),
    ENTITY_ID    VARCHAR(100),
    DETAILS      CLOB,
    PERFORMED_BY VARCHAR(100),
    SOURCE_SYSTEM VARCHAR(50),
    STATUS       VARCHAR(30),
    CREATED_DATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Source credibility configuration
CREATE TABLE IF NOT EXISTS SOURCE_CREDIBILITY (
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE_SYSTEM    VARCHAR(50) NOT NULL UNIQUE,
    CREDIBILITY_SCORE DOUBLE     NOT NULL,
    DESCRIPTION      VARCHAR(255),
    STATUS           VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE     TIMESTAMP
);

-- IAM verified identities
CREATE TABLE IF NOT EXISTS VERIFIED_IDENTITIES (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    GOLDEN_ID       VARCHAR(64) NOT NULL,
    IAM_ID          VARCHAR(100),
    ITSC_ACCOUNT    VARCHAR(100),
    ROLES           CLOB,
    VERIFIED_STATUS VARCHAR(30) DEFAULT 'PENDING',
    LAST_SYNC_DATE  TIMESTAMP,
    CREATED_DATE    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS IDX_IDENTITIES_EMAIL     ON IDENTITIES(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_IDENTITIES_HKID      ON IDENTITIES(HKID);
CREATE INDEX IF NOT EXISTS IDX_IDENTITIES_STAFF_ID  ON IDENTITIES(STAFF_ID);
CREATE INDEX IF NOT EXISTS IDX_IDENTITIES_STATUS    ON IDENTITIES(STATUS);
CREATE INDEX IF NOT EXISTS IDX_IDENTITY_LINKS_GID   ON IDENTITY_LINKS(GOLDEN_ID);
CREATE INDEX IF NOT EXISTS IDX_MANUAL_REVIEWS_STATUS ON MANUAL_REVIEWS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOGS_ENTITY    ON AUDIT_LOGS(ENTITY_ID);

-- Seed source credibility data
INSERT INTO SOURCE_CREDIBILITY (SOURCE_SYSTEM, CREDIBILITY_SCORE, DESCRIPTION, STATUS)
VALUES ('CRM', 1.0, 'CRM - master data, highest credibility', 'ACTIVE');
INSERT INTO SOURCE_CREDIBILITY (SOURCE_SYSTEM, CREDIBILITY_SCORE, DESCRIPTION, STATUS)
VALUES ('ADMS', 0.9, 'ADMS - admissions system', 'ACTIVE');
INSERT INTO SOURCE_CREDIBILITY (SOURCE_SYSTEM, CREDIBILITY_SCORE, DESCRIPTION, STATUS)
VALUES ('ATTENDANCE', 0.9, 'Attendance system', 'ACTIVE');
INSERT INTO SOURCE_CREDIBILITY (SOURCE_SYSTEM, CREDIBILITY_SCORE, DESCRIPTION, STATUS)
VALUES ('EVENT_SYSTEM', 0.8, 'Event management system', 'ACTIVE');
INSERT INTO SOURCE_CREDIBILITY (SOURCE_SYSTEM, CREDIBILITY_SCORE, DESCRIPTION, STATUS)
VALUES ('THIRD_PARTY', 0.7, '3rd-party forms and integrations', 'ACTIVE');
