CREATE TABLE identity_links (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_id NUMBER NOT NULL,
  source_system VARCHAR2(100) NOT NULL,
  source_record_id VARCHAR2(255) NOT NULL,
  CONSTRAINT fk_identity_links_identity FOREIGN KEY (identity_id) REFERENCES identities(id)
);
CREATE INDEX idx_identity_links_identity_id ON identity_links(identity_id);
CREATE UNIQUE INDEX idx_identity_links_source ON identity_links(source_system, source_record_id);
