CREATE TABLE identity_graph (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_identity_id NUMBER NOT NULL,
  to_identity_id NUMBER NOT NULL,
  relationship_type VARCHAR2(50) NOT NULL,
  strength NUMBER(5,4) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_identity_graph_from FOREIGN KEY (from_identity_id) REFERENCES identities(id),
  CONSTRAINT fk_identity_graph_to FOREIGN KEY (to_identity_id) REFERENCES identities(id)
);
CREATE INDEX idx_identity_graph_from ON identity_graph(from_identity_id);
CREATE INDEX idx_identity_graph_to ON identity_graph(to_identity_id);
