CREATE TABLE manual_reviews (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incoming_record_id VARCHAR2(255) NOT NULL,
  candidate_identity_id VARCHAR2(255),
  confidence NUMBER(5,4) NOT NULL,
  status VARCHAR2(30) NOT NULL,
  reason VARCHAR2(2000),
  decision VARCHAR2(2000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_manual_reviews_status ON manual_reviews(status);
