CREATE TABLE source_credibility (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system VARCHAR2(100) NOT NULL UNIQUE,
  multiplier NUMBER(5,4) NOT NULL,
  description VARCHAR2(500)
);
INSERT INTO source_credibility(source_system, multiplier, description) VALUES ('CRM', 1.0, 'Master data source');
INSERT INTO source_credibility(source_system, multiplier, description) VALUES ('ADMS', 0.9, 'Admissions and attendance source');
INSERT INTO source_credibility(source_system, multiplier, description) VALUES ('ATTENDANCE', 0.9, 'Attendance source');
INSERT INTO source_credibility(source_system, multiplier, description) VALUES ('3RD_PARTY', 0.7, 'Third-party forms');
